// Static list of all Colombian municipalities and main towns/corregimientos
// Generated dynamically to avoid runtime API dependencies for the primary country
export const CIUDADES_COLOMBIA = [
    "Abejorral",
    "Abrego",
    "Ábrego",
    "Abriaquí",
    "Acacias",
    "Acacías",
    "Acandí",
    "Acevedo",
    "Achí",
    "Agua de Dios",
    "Aguachica",
    "Aguada",
    "Aguadas",
    "Aguazul",
    "Agustín Codazzi",
    "Aipe",
    "Albán",
    "Albania",
    "Alcalá",
    "Aldana",
    "Alejandría",
    "Algarrobo",
    "Algeciras",
    "Almaguer",
    "Almeida",
    "Alpujarra",
    "Altamira",
    "Alto Baudo",
    "Altos del Rosario",
    "Alvarado",
    "Amagá",
    "Amalfi",
    "Ambalema",
    "Anaime",
    "Anapoima",
    "Ancuya",
    "Ancuyá",
    "Andalucía",
    "Andes",
    "Angelópolis",
    "Angostura",
    "Anolaima",
    "Anserma",
    "Ansermanuevo",
    "Antioquia",
    "Anza",
    "Anzoátegui",
    "Apartadó",
    "Apía",
    "Apulo",
    "Aquitania",
    "Aracataca",
    "Aranzazu",
    "Aratoca",
    "Arauca",
    "Arauquita",
    "Arbeláez",
    "Arboleda",
    "Arboledas",
    "Arboletes",
    "Arcabuco",
    "Arenal",
    "Argelia",
    "Ariguaní",
    "Arjona",
    "Armenia",
    "Armero",
    "Armero-Guyabal",
    "Arroyohondo",
    "Astrea",
    "Ataco",
    "Atlantico",
    "Atrato",
    "Ayapel",
    "Bagadó",
    "Bahía Solano",
    "Bajo Baudó",
    "Balboa",
    "Baranoa",
    "Baraya",
    "Barbacoas",
    "Barbosa",
    "Barichara",
    "Barranca de Upía",
    "Barrancabermeja",
    "Barrancas",
    "Barranco de Loba",
    "Barranco Minas",
    "Barranquilla",
    "Barrio San Luis",
    "Becerril",
    "Belalcázar",
    "Belén",
    "Belén de Los Andaquies",
    "Belén de los Andaquíes",
    "Belén de Umbría",
    "Bellavista",
    "Bello",
    "Belmira",
    "Beltrán",
    "Berbeo",
    "Bermudez",
    "Betania",
    "Betéitiva",
    "Betulia",
    "Bituima",
    "Boavita",
    "Bochalema",
    "Bogota",
    "Bojacá",
    "Bojaya",
    "Bolívar",
    "Boyaca",
    "Boyacá",
    "Briceño",
    "Bucaramanga",
    "Bucarasica",
    "Buenaventura",
    "Buenavista",
    "Buenos Aires",
    "Buesaco",
    "Buga",
    "Bugalagrande",
    "Buriticá",
    "Busbanzá",
    "Cabrera",
    "Cabuyaro",
    "Cacahual",
    "Cáceres",
    "Cachipay",
    "Cáchira",
    "Cachirá",
    "Cácota",
    "Caicedo",
    "Caicedonia",
    "Caimito",
    "Cajamarca",
    "Cajibío",
    "Cajica",
    "Cajicá",
    "Calamar",
    "Calarca",
    "Calarcá",
    "Caldas",
    "Caldono",
    "Cali",
    "California",
    "Calima",
    "Caloto",
    "Campamento",
    "Campo Alegre",
    "Campo de la Cruz",
    "Campoalegre",
    "Campohermoso",
    "Canalete",
    "Candelaria",
    "Cantagallo",
    "Cañasgordas",
    "Caparrapí",
    "Capitanejo",
    "Cáqueza",
    "Caqueza",
    "Caracolí",
    "Caramanta",
    "Carcasí",
    "Carepa",
    "Carlosama",
    "Carmen de Apicalá",
    "Carmen de Carupa",
    "Carmen de Viboral",
    "Carmen del Darien",
    "Carolina",
    "Cartagena",
    "Cartagena del Chairá",
    "Cartago",
    "Caruru",
    "Casabianca",
    "Castilla la Nueva",
    "Cauca",
    "Caucasia",
    "Cepitá",
    "Cereté",
    "Cerinza",
    "Cerrito",
    "Cerro de San Antonio",
    "Cerro San Antonio",
    "Cértegui",
    "Chachagüí",
    "Chaguaní",
    "Chalán",
    "Chameza",
    "Chámeza",
    "Chaparral",
    "Charalá",
    "Charta",
    "Chia",
    "Chía",
    "Chibolo",
    "Chicoral",
    "Chigorodó",
    "Chimá",
    "Chima",
    "Chimichagua",
    "Chinácota",
    "Chinavita",
    "Chinchiná",
    "Chinú",
    "Chipaque",
    "Chipatá",
    "Chiquinquira",
    "Chiquinquirá",
    "Chíquiza",
    "Chiriguaná",
    "Chiscas",
    "Chita",
    "Chitagá",
    "Chitaraque",
    "Chivatá",
    "Chivolo",
    "Chivor",
    "Choachí",
    "Chocho",
    "Chocontá",
    "Cicuco",
    "Ciénaga",
    "Ciénaga de Oro",
    "Ciénega",
    "Cimitarra",
    "Circasia",
    "Cisneros",
    "Ciudad Bolívar",
    "Clemencia",
    "Cocorná",
    "Coello",
    "Cogua",
    "Colombia",
    "Colón",
    "Coloso",
    "Colosó",
    "Columbia",
    "Cómbita",
    "Combita",
    "Concepción",
    "Concordia",
    "Condoto",
    "Confines",
    "Consaca",
    "Consacá",
    "Contadero",
    "Contratación",
    "Convención",
    "Copacabana",
    "Coper",
    "Córdoba",
    "Corinto",
    "Coromoro",
    "Corozal",
    "Corrales",
    "Cota",
    "Cotorra",
    "Covarachía",
    "Coveñas",
    "Coyaima",
    "Cravo Norte",
    "Cruces de Anorí",
    "Cuaspud",
    "Cubará",
    "Cubarral",
    "Cucaita",
    "Cucunubá",
    "Cúcuta",
    "Cucutilla",
    "Cuítiva",
    "Cumaral",
    "Cumaribo",
    "Cumbal",
    "Cumbitara",
    "Cunday",
    "Cundinamarca",
    "Curillo",
    "Curití",
    "Curumaní",
    "Dabeiba",
    "Dagua",
    "Darien",
    "Dibulla",
    "Distracción",
    "Doima",
    "Dolores",
    "Don Matías",
    "Donmatías",
    "Dosquebradas",
    "Duitama",
    "Durania",
    "Ebéjico",
    "El Agrado",
    "El Águila",
    "El Bagre",
    "El Banco",
    "El Bordo",
    "El Cairo",
    "El Calvario",
    "El Cantón de San Pablo",
    "El Cantón del San Pablo",
    "El Carmen",
    "El Carmen de Atrato",
    "El Carmen de Bolívar",
    "El Carmen de Chucurí",
    "El Carmen de Viboral",
    "El Castillo",
    "El Cerrito",
    "El Charco",
    "El Cocuy",
    "El Colegio",
    "El Copey",
    "El Doncello",
    "El Dovio",
    "El Encanto",
    "El Espino",
    "El Guacamayo",
    "El Guamo",
    "El Litoral del San Juan",
    "El Maríachi",
    "El Molino",
    "El Paso",
    "El Paujil",
    "El Paujíl",
    "El Peñol",
    "El Peñón",
    "El Piñon",
    "El Piñón",
    "El Playón",
    "El Retén",
    "El Retorno",
    "El Roble",
    "El Rosal",
    "El Rosario",
    "El Santuario",
    "El Tablón",
    "El Tablón de Gómez",
    "El Tambo",
    "El Tarra",
    "El Zulia",
    "Elias",
    "Encino",
    "Enciso",
    "Engativa",
    "Entrerrios",
    "Entrerríos",
    "Envigado",
    "Espinal",
    "Facatativá",
    "Falan",
    "Filadelfia",
    "Filandia",
    "Firavitoba",
    "Flandes",
    "Florencia",
    "Floresta",
    "Florián",
    "Florida",
    "Floridablanca",
    "Fomeque",
    "Fómeque",
    "Fonseca",
    "Fortul",
    "Fosca",
    "Francisco Pizarro",
    "Fredonia",
    "Fresno",
    "Frías",
    "Frontino",
    "Fuente de Oro",
    "Fundacion",
    "Fundación",
    "Funes",
    "Funza",
    "Fúquene",
    "Fusagasuga",
    "Fusagasugá",
    "Gachala",
    "Gachalá",
    "Gachancipá",
    "Gachantivá",
    "Gachetá",
    "Gaitania",
    "Galán",
    "Galapa",
    "Galeras",
    "Gama",
    "Gamarra",
    "Gambita",
    "Gámbita",
    "Gameza",
    "Gámeza",
    "Garagoa",
    "Garzón",
    "Génova",
    "Gigante",
    "Ginebra",
    "Giraldo",
    "Girardot",
    "Girardota",
    "Giron",
    "Girón",
    "Gómez Plata",
    "González",
    "Gramalote",
    "Granada",
    "Guaca",
    "Guacamayas",
    "Guacarí",
    "Guachetá",
    "Guachucal",
    "Guadalajara de Buga",
    "Guadalupe",
    "Guaduas",
    "Guaitarilla",
    "Gualmatán",
    "Guamal",
    "Guamo",
    "Guapi",
    "Guapí",
    "Guapotá",
    "Guaranda",
    "Guarne",
    "Guasca",
    "Guatapé",
    "Guataquí",
    "Guatavita",
    "Guateque",
    "Guática",
    "Guavatá",
    "Guayabal",
    "Guayabal de Siquima",
    "Guayabal de Síquima",
    "Guayabetal",
    "Guayatá",
    "Güepsa",
    "Güicán",
    "Gutiérrez",
    "Hacarí",
    "Hatillo de Loba",
    "Hato",
    "Hato Corozal",
    "Hatonuevo",
    "Heliconia",
    "Herrán",
    "Herveo",
    "Hispania",
    "Hobo",
    "Honda",
    "Ibague",
    "Ibagué",
    "Icononzo",
    "Iles",
    "Imués",
    "Inirida",
    "Inírida",
    "Inzá",
    "Ipiales",
    "Iquira",
    "Iscuandé",
    "Isnos",
    "Istmina",
    "Itagui",
    "Itagüí",
    "Ituango",
    "Iza",
    "Jambaló",
    "Jamundí",
    "Jardín",
    "Jenesano",
    "Jericó",
    "Jerusalén",
    "Jesús María",
    "Jordán",
    "Juan de Acosta",
    "Junín",
    "Juradó",
    "La Apartada",
    "La Belleza",
    "La Calera",
    "La Capilla",
    "La Ceja",
    "La Celia",
    "La Chamba",
    "La Chorrera",
    "La Cruz",
    "La Cumbre",
    "La Dorada",
    "La Esperanza",
    "La Estrella",
    "La Florida",
    "La Gloria",
    "La Guadalupe",
    "La Jagua de Ibirico",
    "La Jagua del Pilar",
    "La Llanada",
    "La Macarena",
    "La Merced",
    "La Mesa",
    "La Montañita",
    "La Palma",
    "La Paz",
    "La Pedrera",
    "La Peña",
    "La Pintada",
    "La Plata",
    "La Playa",
    "La Primavera",
    "La Sierra",
    "La Tebaida",
    "La Tola",
    "La Union",
    "La Unión",
    "La Uvita",
    "La Vega",
    "La Victoria",
    "La Virginia",
    "Labateca",
    "Labranzagrande",
    "Landázuri",
    "Laureles",
    "Lebrija",
    "Lebríja",
    "Leguízamo",
    "Leiva",
    "Lejanías",
    "Lenguazaque",
    "Lérida",
    "Leticia",
    "Líbano",
    "Liborina",
    "Linares",
    "Lloró",
    "López",
    "Lorica",
    "Los Andes",
    "Los Córdobas",
    "Los Palmitos",
    "Los Patios",
    "Los Santos",
    "Lourdes",
    "Luruaco",
    "Macanal",
    "Macaravita",
    "Maceo",
    "Macheta",
    "Machetá",
    "Madrid",
    "Magangué",
    "Magdalena",
    "Magüi",
    "Mahates",
    "Maicao",
    "Majagual",
    "Málaga",
    "Malambo",
    "Mallama",
    "Manatí",
    "Manaure",
    "Manaure Balcón del Cesar",
    "Maní",
    "Manizales",
    "Manta",
    "Manzanares",
    "Mapiripán",
    "Mapiripana",
    "Margarita",
    "María la Baja",
    "Marinilla",
    "Maripí",
    "Marmato",
    "Marquetalia",
    "Marsella",
    "Marulanda",
    "Matanza",
    "Medellín",
    "Medina",
    "Medio Atrato",
    "Medio Baudó",
    "Medio San Juan",
    "Melgar",
    "Mercaderes",
    "Mesetas",
    "Miami",
    "Milán",
    "Miraflores",
    "Miranda",
    "Miriti - Paraná",
    "Mistrató",
    "Mitu",
    "Mitú",
    "Mocoa",
    "Mogotes",
    "Molagavita",
    "Momil",
    "Mompós",
    "Mongua",
    "Monguí",
    "Moniquirá",
    "Montebello",
    "Montecristo",
    "Montelíbano",
    "Montenegro",
    "Montería",
    "Monterrey",
    "Moñitos",
    "Morales",
    "Morelia",
    "Morichal",
    "Morroa",
    "Mosquera",
    "Motavita",
    "Mountain",
    "Municipio de Cartagena de Indias",
    "Municipio de Copacabana",
    "Municipio de López de Micay",
    "Municipio de María la Baja",
    "Municipio de San Pedro de los Milagros",
    "Municipio de San Sebastián de Mariquita",
    "Municipio Hato Corozal",
    "Murillo",
    "Murindó",
    "Mutatá",
    "Mutiscua",
    "Muzo",
    "Nariño",
    "Nataga",
    "Natagaima",
    "Nechí",
    "Necoclí",
    "Neira",
    "Neiva",
    "Nemocón",
    "Nilo",
    "Nimaima",
    "Nobsa",
    "Nocaima",
    "Norcasia",
    "Norosí",
    "Nóvita",
    "Nueva Granada",
    "Nuevo Colón",
    "Nunchía",
    "Nuquí",
    "Obando",
    "Ocamonte",
    "Ocaña",
    "Oiba",
    "Oicatá",
    "Olaya",
    "Olaya Herrera",
    "Onzaga",
    "Oporapa",
    "Orito",
    "Orocué",
    "Ortega",
    "Ospina",
    "Otanche",
    "Ovejas",
    "Pachavita",
    "Pacoa",
    "Pácora",
    "Padilla",
    "Padua",
    "Páez",
    "Paez",
    "Paicol",
    "Pailitas",
    "Paime",
    "Paipa",
    "Paispamba",
    "Pajarito",
    "Palermo",
    "Palestina",
    "Palmar",
    "Palmar de Varela",
    "Palmas del Socorro",
    "Palmira",
    "Palmito",
    "Palocabildo",
    "Pamplona",
    "Pamplonita",
    "Pana Pana",
    "Pandi",
    "Panqueba",
    "Papunaua",
    "Páramo",
    "Paratebueno",
    "Pasca",
    "Pasto",
    "Patía",
    "Pauna",
    "Paya",
    "Payán",
    "Payandé",
    "Paz de Río",
    "Pedraza",
    "Pelaya",
    "Pensilvania",
    "Peñol",
    "Peque",
    "Pereira",
    "Pesca",
    "Pie de Pató",
    "Piedecuesta",
    "Piedrancha",
    "Piedras",
    "Piendamo",
    "Piendamó",
    "Pijao",
    "Pijiño del Carmen",
    "Pinchote",
    "Pinillos",
    "Piojó",
    "Pisba",
    "Pital",
    "Pitalito",
    "Pivijay",
    "Pizarro",
    "Planadas",
    "Planeta Rica",
    "Plato",
    "Playarrica",
    "Policarpa",
    "Polonuevo",
    "Ponedera",
    "Popayan",
    "Popayán",
    "Pore",
    "Potosí",
    "Pradera",
    "Prado",
    "Providencia",
    "Pueblo Nuevo",
    "Pueblo Rico",
    "Pueblorrico",
    "Puebloviejo",
    "Puente Nacional",
    "Puerres",
    "Puerta Roja",
    "Puerto Alegría",
    "Puerto Arica",
    "Puerto Asís",
    "Puerto Berrío",
    "Puerto Bogotá",
    "Puerto Boyacá",
    "Puerto Carreño",
    "Puerto Colombia",
    "Puerto Concordia",
    "Puerto Escondido",
    "Puerto Gaitán",
    "Puerto Guzmán",
    "Puerto Leguízamo",
    "Puerto Libertador",
    "Puerto Lleras",
    "Puerto López",
    "Puerto Nare",
    "Puerto Nariño",
    "Puerto Parra",
    "Puerto Rico",
    "Puerto Rondón",
    "Puerto Salgar",
    "Puerto Santander",
    "Puerto Tejada",
    "Puerto Triunfo",
    "Puerto Wilches",
    "Puerto Yuca",
    "Pulí",
    "Pupiales",
    "Puracé",
    "Purificacion",
    "Purificación",
    "Purísima",
    "Purísima de la Concepción",
    "Quebradanegra",
    "Quetame",
    "Quibdó",
    "Quimbaya",
    "Quinchía",
    "Quípama",
    "Quipile",
    "Ragonvalia",
    "Ramiriquí",
    "Ráquira",
    "Recetor",
    "Regidor",
    "Remedios",
    "Remolino",
    "Repelón",
    "Restrepo",
    "Retiro",
    "Ricaurte",
    "Río de Oro",
    "Río Iro",
    "Río Quito",
    "Río Viejo",
    "Rioblanco",
    "Riofrío",
    "Riohacha",
    "Rionegro",
    "Riosucio",
    "Risaralda",
    "Rivera",
    "Roberto Payán",
    "Roldanillo",
    "Roncesvalles",
    "Rondón",
    "Rosas",
    "Rovira",
    "Sabana de Torres",
    "Sabanagrande",
    "Sabanalarga",
    "Sabanas de San Angel",
    "Sabaneta",
    "Saboyá",
    "Sácama",
    "Sachica",
    "Sáchica",
    "Sahagún",
    "Saladoblanco",
    "Salahonda",
    "Salamina",
    "Salazar",
    "Saldaña",
    "Salento",
    "Salgar",
    "Samacá",
    "Samaná",
    "Samaniego",
    "Sampués",
    "San Agustín",
    "San Alberto",
    "San Andrés",
    "San Andrés de Cuerquía",
    "San Andres de Tumaco",
    "San Andrés Sotavento",
    "San Antero",
    "San Antonio",
    "San Antonio del Tequendama",
    "San Benito",
    "San Benito Abad",
    "San Bernardo",
    "San Bernardo del Viento",
    "San Calixto",
    "San Carlos",
    "San Carlos de Guaroa",
    "San Cayetano",
    "San Clemente",
    "San Cristóbal",
    "San Diego",
    "San Eduardo",
    "San Estanislao",
    "San Felipe",
    "San Fernando",
    "San Francisco",
    "San Gil",
    "San Jacinto",
    "San Jacinto del Cauca",
    "San Jerónimo",
    "San Joaquín",
    "San José",
    "San José de la Montaña",
    "San José de Miranda",
    "San José de Pare",
    "San José del Fragua",
    "San José del Guaviare",
    "San José del Palmar",
    "San Juan de Arama",
    "San Juan de Betulia",
    "San Juan de Río Seco",
    "San Juan de Urabá",
    "San Juan del Cesar",
    "San Juan Nepomuceno",
    "San Lorenzo",
    "San Luis",
    "San Luis de Gaceno",
    "San Luis de Palenque",
    "San Luis de Sincé",
    "San Marcos",
    "San Martin",
    "San Martín",
    "San Martín de Loba",
    "San Mateo",
    "San Miguel",
    "San Miguel de Sema",
    "San Onofre",
    "San Pablo",
    "San Pablo de Borbur",
    "San Pedro",
    "San Pedro de Cartago",
    "San Pedro de Uraba",
    "San Pedro de Urabá",
    "San Pelayo",
    "San Rafael",
    "San Roque",
    "San Sebastián",
    "San Sebastián de Mariquita",
    "San Vicente",
    "San Vicente de Chucurí",
    "San Vicente Ferrer",
    "San Zenón",
    "Sandoná",
    "Santa Ana",
    "Santa Bárbara",
    "Santa Bárbara de Pinto",
    "Santa Catalina",
    "Santa Fe de Antioquia",
    "Santa Genoveva de Docordó",
    "Santa Isabel",
    "Santa Lucía",
    "Santa María",
    "Santa Marta",
    "Santa Rosa",
    "Santa Rosa de Cabal",
    "Santa Rosa de Osos",
    "Santa Rosa de Viterbo",
    "Santa Rosa del Sur",
    "Santa Rosalia",
    "Santa Rosalía",
    "Santa Sofía",
    "Santacruz",
    "Santafé de Antioquia",
    "Santana",
    "Santander de Quilichao",
    "Santiago",
    "Santiago de Cali",
    "Santiago de Tolú",
    "Santiago Pérez",
    "Santo Domingo",
    "Santo Tomás",
    "Santuario",
    "Sapuyes",
    "Saravena",
    "Sardinata",
    "Sasaima",
    "Sativanorte",
    "Sativasur",
    "Segovia",
    "Sesquilé",
    "Sevilla",
    "Siachoque",
    "Sibaté",
    "Sibundoy",
    "Silos",
    "Silvania",
    "Silvia",
    "Simacota",
    "Simijaca",
    "Simití",
    "Sincelejo",
    "Sipí",
    "Sitionuevo",
    "Soacha",
    "Soatá",
    "Socha",
    "Socha Viejo",
    "Socorro",
    "Socotá",
    "Sogamoso",
    "Solano",
    "Soledad",
    "Somondoco",
    "Sonson",
    "Sonsón",
    "Sopetrán",
    "Soplaviento",
    "Sopo",
    "Sopó",
    "Sora",
    "Soracá",
    "Sotaquirá",
    "Sotara",
    "Sotomayor",
    "Suaita",
    "Suan",
    "Suárez",
    "Suaza",
    "Subachoque",
    "Sucre",
    "Suesca",
    "Supatá",
    "Supía",
    "Suratá",
    "Susa",
    "Susacón",
    "Sutamarchán",
    "Sutatausa",
    "Sutatenza",
    "Tabio",
    "Tadó",
    "Talaigua Nuevo",
    "Talaigua Viejo",
    "Tamalameque",
    "Támara",
    "Tame",
    "Támesis",
    "Taminango",
    "Tangua",
    "Taraira",
    "Tarapaca",
    "Tarapacá",
    "Tarazá",
    "Tarqui",
    "Tarso",
    "Tasco",
    "Tauramena",
    "Tausa",
    "Tello",
    "Tena",
    "Tenerife",
    "Tenjo",
    "Tenza",
    "Teruel",
    "Tesalia",
    "Tibacuy",
    "Tibaná",
    "Tibasosa",
    "Tibirita",
    "Tibú",
    "Tierralta",
    "Timana",
    "Timbiquí",
    "Tinjacá",
    "Tipacoque",
    "Tiquisio",
    "Titiribí",
    "Toca",
    "Tocaima",
    "Tocancipa",
    "Tocancipá",
    "Togüí",
    "Toledo",
    "Tolú",
    "Tolú Viejo",
    "Tona",
    "Tópaga",
    "Topaipí",
    "Toribio",
    "Toribío",
    "Toro",
    "Tota",
    "Totoró",
    "Tres Esquinas",
    "Trinidad",
    "Trujillo",
    "Tubará",
    "Tuluá",
    "Tumaco",
    "Tunja",
    "Tununguá",
    "Túquerres",
    "Turbaco",
    "Turbaná",
    "Turbo",
    "Turmequé",
    "Tuta",
    "Tutazá",
    "Ubalá",
    "Ubaque",
    "Ulloa",
    "Umbita",
    "Úmbita",
    "Une",
    "Unguía",
    "Unión Panamericana",
    "Uramita",
    "Uribia",
    "Urrao",
    "Urumita",
    "Usiacurí",
    "Útica",
    "Valdivia",
    "Valencia",
    "Valle de San José",
    "Valle de San Juan",
    "Valle del Guamuez",
    "Valledupar",
    "Valparaíso",
    "Vegachí",
    "Velez",
    "Vélez",
    "Venadillo",
    "Venecia",
    "Ventaquemada",
    "Vergara",
    "Versalles",
    "Vetas",
    "Vianí",
    "Victoria",
    "Vigía del Fuerte",
    "Vijes",
    "Villa de Leyva",
    "Villa de San Diego de Ubate",
    "Villa de San Diego de Ubaté",
    "Villa del Rosario",
    "Villa Rica",
    "Villagarzón",
    "Villagómez",
    "Villahermosa",
    "Villamaria",
    "Villamaría",
    "Villanueva",
    "Villapinzón",
    "Villarrica",
    "Villavicencio",
    "Villavieja",
    "Villeta",
    "Viotá",
    "Viracachá",
    "Vistahermosa",
    "Viterbo",
    "Yacopí",
    "Yacuanquer",
    "Yaguará",
    "Yalí",
    "Yarumal",
    "Yavaraté",
    "Yolombó",
    "Yondó",
    "Yopal",
    "Yotoco",
    "Yumbo",
    "Zambrano",
    "Zapatoca",
    "Zapayán",
    "Zaragoza",
    "Zarzal",
    "Zetaquira",
    "Zipacón",
    "Zipaquirá",
    "Zona Bananera"
];
