export const TIPOS_DOCUMENTO = [
    "Pasaporte",
    "Documento de identificación para extranjeros",
    "PEP",
    "Registro Profesional",
    "Carné diplomático",
    "Salvoconducto",
    "Permiso por protección temporal",
    "Certificado de nacido vivo",
    "Sin identificación",
    "Cédula de ciudadanía",
    "NIT de otro país",
    "Tarjeta de identidad",
    "Cédula de extranjería",
    "Registro civil de nacimiento",
    "Número único de identificación personal",
    "Menor sin identificar",
    "Adulto sin identificar",
    "NIT"
];

export const SEXOS = ["Masculino", "Femenino", "Otro"];

export const ESTADOS_CIVILES = [
    "Soltero",
    "Casado",
    "Unión libre",
    "Divorciado",
    "Viudo",
    "Otros"
];

export const ESTRATOS = ["1", "2", "3", "4", "5", "6"];

export const ZONAS_RESIDENCIALES = ["Urbano", "Rural"];

export const PARENTESCOS = [
    "Padre/Madre",
    "Hijo/a",
    "Cónyuge/Compañero/a",
    "Hermano/a",
    "Abuelo/a",
    "Nieto/a",
    "Tío/a",
    "Primo/a",
    "Sobrino/a",
    "Suegro/a",
    "Cuñado/a",
    "Otro"
];

export const MEDIOS_CONOCIMIENTO = [
    "Fachada",
    "Referido",
    "Tik Tok",
    "Radio",
    "Facebook",
    "Instagram",
    "Youtube",
    "Google",
    "Volante",
    "Prensa",
    "Otro"
];

export const PAISES = [
    "Albania", "Antártida", "Argelia", "Samoa Americana", "Andorra", "Angola", "Antigua y Barbuda", "Azerbaiyán", "Argentina", "Australia", "Austria", "Bahamas (las)", "Bahrein", "Bangladesh", "Armenia", "Barbados", "Bélgica", "Bermudas", "Bhután", "Bolivia", "Bosnia y Herzegovina", "Botswana", "Brasil", "Belice", "Territorio Británico del Océano Índico (el)", "Islas Vírgenes británicas", "Brunei Darussalam", "Bouvet", "Norfolk", "Salomón", "Bulgaria", "Myanmar", "Burundi", "Belarús", "Camboya", "Camerún", "Canadá", "Cabo Verde", "Caimán Islas", "República Centroafricana", "Sri Lanka", "Chad", "Chile", "China", "Taiwán", "Isla de Navidad", "Cocos Islas", "Colombia", "Comoras (las)", "Mayotte", "Cook Islas", "Costa Rica", "Croacia", "Cuba", "Chipre", "Chequia", "Benin", "Dinamarca", "Dominica", "República Dominicana", "Ecuador", "El Salvador", "Guinea Ecuatorial", "Etiopía", "Eritrea", "Estonia", "Feroe Islas", "Malvinas Islas", "Georgia del Sur", "Fiji", "Finlandia", "Francia", "Guayana Francesa", "Polinesia Francesa", "Tierras Australes Francesas", "Djibouti", "Gabón", "Georgia", "Gambia (la)", "Alemania", "Ghana", "Gibraltar", "Kiribati", "Grecia", "Groenlandia", "Granada", "Guadeloupe", "Guam", "Guatemala", "Guinea", "Guyana", "Haití", "Heard", "Santa Sede", "Honduras", "Hong Kong", "Hungría", "Islandia", "India", "Indonesia", "Irán", "Iraq", "Irlanda", "Israel", "Italia", "Côte d'Ivoire", "Jamaica", "Japón", "Kazajstán", "Jordania", "Kenya", "Corea del Sur", "Kuwait", "Kirguistán", "Lao", "Líbano", "Lesotho", "Letonia", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macao", "Madagascar", "Malawi", "Malasia", "Maldivas", "Malí", "Malta", "Martinique", "Mauritania", "Mauricio", "México", "Mónaco", "Mongolia", "Moldova", "Montserrat", "Marruecos", "Mozambique", "Omán", "Namibia", "Nauru", "Nepal", "Países Bajos", "Curazao", "Aruba", "Nueva Caledonia", "Vanuatu", "Nueva Zelandia", "Nicaragua", "Níger", "Nigeria", "Niue", "Noruega", "Marianas del Norte", "Islas Ultramarinas Menores de los Estados Unidos", "Marshall Islas", "Palau", "Pakistán", "Panamá", "Papua Nueva Guinea", "Paraguay", "Perú", "Filipinas (las)", "Pitcairn", "Polonia", "Portugal", "Guinea Bissau", "Timor-Leste", "Puerto Rico", "Qatar", "Reunión", "Rumania", "Rusia", "Rwanda", "Santa Helena", "Anguila", "Santa Lucía", "San Pedro y Miquelón", "San Vicente y las Granadinas", "San Marino", "Santo Tomé y Príncipe", "Arabia Saudita", "Senegal", "Seychelles", "Sierra leona", "Singapur", "Eslovaquia", "Viet Nam", "Eslovenia", "Somalia", "Sudáfrica", "Zimbabwe", "España", "Sahara Occidental", "Sudán", "Suriname", "Svalbard y Jan Mayen", "Swazilandia", "Suecia", "Suiza", "República Árabe Siria", "Tayikistán", "Tailandia", "Togo", "Tokelau", "Tonga", "Trinidad y Tabago", "Emiratos Árabes Unidos", "Túnez", "Turquía", "Turkmenistán", "Turcas y Caicos Islas", "Tuvalu", "Uganda", "Ucrania", "Egipto", "Reino Unido de Gran Bretaña e Irlanda del Norte", "Tanzania", "Estados Unidos", "Islas Vírgenes de los Estados Unidos", "Burkina Faso", "Uruguay", "Uzbekistán", "Venezuela", "Wallis y Futuna", "Samoa", "Yemen", "Zambia", "Congo", "Micronesia", "Macedonia", "Saint Kitts y Nevis"
];

export const TIPOS_VINCULACION = [
    "Contributivo cotizante - 01",
    "Contributivo beneficiario - 02",
    "Contributivo adicional - 03",
    "Subsidiado - 04",
    "No afiliado - 05",
    "Especiales o de Excepción cotizante - 06",
    "Especiales o de Excepción beneficiario - 07",
    "Tomador/Amparado ARL - 09",
    "Tomador/Amparado SOAT - 10",
    "Tomador/Amparado Planes voluntarios de salud - 11",
    "Particular - 12",
    "Especial o Excepcion no cotizante Ley 352 de 1997 - 13",
    "Vinculado -"
];

export const PREFIJOS_TELEFONICOS = [
    { pais: "Albania", prefijo: "+355" },
    { pais: "Antártida", prefijo: "+0" },
    { pais: "Argelia", prefijo: "+213" },
    { pais: "Samoa Americana", prefijo: "+1" },
    { pais: "Andorra", prefijo: "+376" },
    { pais: "Angola", prefijo: "+244" },
    { pais: "Antigua y Barbuda", prefijo: "+1" },
    { pais: "Azerbaiyán", prefijo: "+994" },
    { pais: "Argentina", prefijo: "+54" },
    { pais: "Australia", prefijo: "+61" },
    { pais: "Austria", prefijo: "+43" },
    { pais: "Bahamas (las)", prefijo: "+1" },
    { pais: "Bahrein", prefijo: "+973" },
    { pais: "Bangladesh", prefijo: "+880" },
    { pais: "Armenia", prefijo: "+374" },
    { pais: "Barbados", prefijo: "+1" },
    { pais: "Bélgica", prefijo: "+32" },
    { pais: "Bermudas", prefijo: "+1" },
    { pais: "Bhután", prefijo: "+975" },
    { pais: "Bolivia", prefijo: "+591" },
    { pais: "Bosnia y Herzegovina", prefijo: "+387" },
    { pais: "Botswana", prefijo: "+267" },
    { pais: "Brasil", prefijo: "+55" },
    { pais: "Belice", prefijo: "+501" },
    { pais: "Territorio Británico del Océano Índico (el)", prefijo: "+246" },
    { pais: "Islas Vírgenes británicas", prefijo: "+1" },
    { pais: "Brunei Darussalam", prefijo: "+673" },
    { pais: "Bouvet", prefijo: "+0" },
    { pais: "Norfolk", prefijo: "+672" },
    { pais: "Salomón", prefijo: "+677" },
    { pais: "Bulgaria", prefijo: "+359" },
    { pais: "Myanmar", prefijo: "+95" },
    { pais: "Burundi", prefijo: "+257" },
    { pais: "Belarús", prefijo: "+375" },
    { pais: "Camboya", prefijo: "+855" },
    { pais: "Camerún", prefijo: "+237" },
    { pais: "Canadá", prefijo: "+1" },
    { pais: "Cabo Verde", prefijo: "+238" },
    { pais: "Caimán Islas", prefijo: "+1" },
    { pais: "República Centroafricana", prefijo: "+236" },
    { pais: "Sri Lanka", prefijo: "+94" },
    { pais: "Chad", prefijo: "+235" },
    { pais: "Chile", prefijo: "+56" },
    { pais: "China", prefijo: "+86" },
    { pais: "Taiwán", prefijo: "+886" },
    { pais: "Isla de Navidad", prefijo: "+61" },
    { pais: "Cocos Islas", prefijo: "+61" },
    { pais: "Colombia", prefijo: "+57" },
    { pais: "Comoras (las)", prefijo: "+269" },
    { pais: "Mayotte", prefijo: "+262" },
    { pais: "Cook Islas", prefijo: "+682" },
    { pais: "Costa Rica", prefijo: "+506" },
    { pais: "Croacia", prefijo: "+385" },
    { pais: "Cuba", prefijo: "+53" },
    { pais: "Chipre", prefijo: "+357" },
    { pais: "Chequia", prefijo: "+420" },
    { pais: "Benin", prefijo: "+229" },
    { pais: "Dinamarca", prefijo: "+45" },
    { pais: "Dominica", prefijo: "+1" },
    { pais: "República Dominicana", prefijo: "+1" },
    { pais: "Ecuador", prefijo: "+593" },
    { pais: "El Salvador", prefijo: "+503" },
    { pais: "Guinea Ecuatorial", prefijo: "+240" },
    { pais: "Etiopía", prefijo: "+251" },
    { pais: "Eritrea", prefijo: "+291" },
    { pais: "Estonia", prefijo: "+372" },
    { pais: "Feroe Islas", prefijo: "+298" },
    { pais: "Malvinas Islas", prefijo: "+500" },
    { pais: "Georgia del Sur", prefijo: "+995" },
    { pais: "Fiji", prefijo: "+679" },
    { pais: "Finlandia", prefijo: "+358" },
    { pais: "Francia", prefijo: "+33" },
    { pais: "Guayana Francesa", prefijo: "+594" },
    { pais: "Polinesia Francesa", prefijo: "+689" },
    { pais: "Tierras Australes Francesas", prefijo: "+0" },
    { pais: "Djibouti", prefijo: "+253" },
    { pais: "Gabón", prefijo: "+241" },
    { pais: "Georgia", prefijo: "+995" },
    { pais: "Gambia (la)", prefijo: "+220" },
    { pais: "Alemania", prefijo: "+49" },
    { pais: "Ghana", prefijo: "+233" },
    { pais: "Gibraltar", prefijo: "+350" },
    { pais: "Kiribati", prefijo: "+686" },
    { pais: "Grecia", prefijo: "+30" },
    { pais: "Groenlandia", prefijo: "+299" },
    { pais: "Granada", prefijo: "+0" },
    { pais: "Guadeloupe", prefijo: "+590" },
    { pais: "Guam", prefijo: "+1" },
    { pais: "Guatemala", prefijo: "+502" },
    { pais: "Guinea", prefijo: "+224" },
    { pais: "Guyana", prefijo: "+592" },
    { pais: "Haití", prefijo: "+509" },
    { pais: "Heard", prefijo: "+0" },
    { pais: "Santa Sede", prefijo: "+39" },
    { pais: "Honduras", prefijo: "+504" },
    { pais: "Hong Kong", prefijo: "+852" },
    { pais: "Hungría", prefijo: "+36" },
    { pais: "Islandia", prefijo: "+354" },
    { pais: "India", prefijo: "+91" },
    { pais: "Indonesia", prefijo: "+62" },
    { pais: "Irán", prefijo: "+98" },
    { pais: "Iraq", prefijo: "+964" },
    { pais: "Irlanda", prefijo: "+353" },
    { pais: "Israel", prefijo: "+972" },
    { pais: "Italia", prefijo: "+39" },
    { pais: "Côte d'Ivoire", prefijo: "+225" },
    { pais: "Jamaica", prefijo: "+1" },
    { pais: "Japón", prefijo: "+81" },
    { pais: "Kazajstán", prefijo: "+7" },
    { pais: "Jordania", prefijo: "+962" },
    { pais: "Kenya", prefijo: "+254" },
    { pais: "Corea del Sur", prefijo: "+82" },
    { pais: "Kuwait", prefijo: "+965" },
    { pais: "Kirguistán", prefijo: "+996" },
    { pais: "Lao", prefijo: "+856" },
    { pais: "Líbano", prefijo: "+961" },
    { pais: "Lesotho", prefijo: "+266" },
    { pais: "Letonia", prefijo: "+371" },
    { pais: "Liberia", prefijo: "+231" },
    { pais: "Libia", prefijo: "+218" },
    { pais: "Liechtenstein", prefijo: "+423" },
    { pais: "Lituania", prefijo: "+370" },
    { pais: "Luxemburgo", prefijo: "+352" },
    { pais: "Macao", prefijo: "+853" },
    { pais: "Madagascar", prefijo: "+261" },
    { pais: "Malawi", prefijo: "+265" },
    { pais: "Malasia", prefijo: "+60" },
    { pais: "Maldivas", prefijo: "+960" },
    { pais: "Malí", prefijo: "+223" },
    { pais: "Malta", prefijo: "+356" },
    { pais: "Martinique", prefijo: "+596" },
    { pais: "Mauritania", prefijo: "+222" },
    { pais: "Mauricio", prefijo: "+230" },
    { pais: "México", prefijo: "+52" },
    { pais: "Mónaco", prefijo: "+377" },
    { pais: "Mongolia", prefijo: "+976" },
    { pais: "Moldova", prefijo: "+373" },
    { pais: "Montserrat", prefijo: "+1" },
    { pais: "Marruecos", prefijo: "+212" },
    { pais: "Mozambique", prefijo: "+258" },
    { pais: "Omán", prefijo: "+968" },
    { pais: "Namibia", prefijo: "+264" },
    { pais: "Nauru", prefijo: "+674" },
    { pais: "Nepal", prefijo: "+977" },
    { pais: "Países Bajos", prefijo: "+31" },
    { pais: "Curazao", prefijo: "+599" },
    { pais: "Aruba", prefijo: "+297" },
    { pais: "Nueva Caledonia", prefijo: "+687" },
    { pais: "Vanuatu", prefijo: "+678" },
    { pais: "Nueva Zelandia", prefijo: "+64" },
    { pais: "Nicaragua", prefijo: "+505" },
    { pais: "Níger", prefijo: "+227" },
    { pais: "Nigeria", prefijo: "+234" },
    { pais: "Niue", prefijo: "+683" },
    { pais: "Noruega", prefijo: "+47" },
    { pais: "Marianas del Norte", prefijo: "+1" },
    { pais: "Islas Ultramarinas Menores de los Estados Unidos", prefijo: "+699" },
    { pais: "Marshall Islas", prefijo: "+692" },
    { pais: "Palau", prefijo: "+680" },
    { pais: "Pakistán", prefijo: "+92" },
    { pais: "Panamá", prefijo: "+507" },
    { pais: "Papua Nueva Guinea", prefijo: "+675" },
    { pais: "Paraguay", prefijo: "+595" },
    { pais: "Perú", prefijo: "+51" },
    { pais: "Filipinas (las)", prefijo: "+63" },
    { pais: "Pitcairn", prefijo: "+0" },
    { pais: "Polonia", prefijo: "+48" },
    { pais: "Portugal", prefijo: "+351" },
    { pais: "Guinea Bissau", prefijo: "+245" },
    { pais: "Timor-Leste", prefijo: "+670" },
    { pais: "Puerto Rico", prefijo: "+1" },
    { pais: "Qatar", prefijo: "+974" },
    { pais: "Reunión", prefijo: "+0" },
    { pais: "Rumania", prefijo: "+40" },
    { pais: "Rusia", prefijo: "+7" },
    { pais: "Rwanda", prefijo: "+250" },
    { pais: "Santa Helena", prefijo: "+290" },
    { pais: "Anguila", prefijo: "+1" },
    { pais: "Santa Lucía", prefijo: "+1" },
    { pais: "San Pedro y Miquelón", prefijo: "+508" },
    { pais: "San Vicente y las Granadinas", prefijo: "+1" },
    { pais: "San Marino", prefijo: "+378" },
    { pais: "Santo Tomé y Príncipe", prefijo: "+239" },
    { pais: "Arabia Saudita", prefijo: "+966" },
    { pais: "Senegal", prefijo: "+221" },
    { pais: "Seychelles", prefijo: "+248" },
    { pais: "Sierra leona", prefijo: "+232" },
    { pais: "Singapur", prefijo: "+65" },
    { pais: "Eslovaquia", prefijo: "+421" },
    { pais: "Viet Nam", prefijo: "+84" },
    { pais: "Eslovenia", prefijo: "+386" },
    { pais: "Somalia", prefijo: "+252" },
    { pais: "Sudáfrica", prefijo: "+27" },
    { pais: "Zimbabwe", prefijo: "+263" },
    { pais: "España", prefijo: "+34" },
    { pais: "Sahara Occidental", prefijo: "+212" },
    { pais: "Sudán", prefijo: "+249" },
    { pais: "Suriname", prefijo: "+597" },
    { pais: "Svalbard y Jan Mayen", prefijo: "+47" },
    { pais: "Swazilandia", prefijo: "+268" },
    { pais: "Suecia", prefijo: "+46" },
    { pais: "Suiza", prefijo: "+41" },
    { pais: "República Árabe Siria", prefijo: "+963" },
    { pais: "Tayikistán", prefijo: "+992" },
    { pais: "Tailandia", prefijo: "+66" },
    { pais: "Togo", prefijo: "+228" },
    { pais: "Tokelau", prefijo: "+690" },
    { pais: "Tonga", prefijo: "+676" },
    { pais: "Trinidad y Tabago", prefijo: "+1" },
    { pais: "Emiratos Árabes Unidos", prefijo: "+971" },
    { pais: "Túnez", prefijo: "+216" },
    { pais: "Turquía", prefijo: "+90" },
    { pais: "Turkmenistán", prefijo: "+993" },
    { pais: "Turcas y Caicos Islas", prefijo: "+649" },
    { pais: "Tuvalu", prefijo: "+688" },
    { pais: "Uganda", prefijo: "+256" },
    { pais: "Ucrania", prefijo: "+380" },
    { pais: "Egipto", prefijo: "+20" },
    { pais: "Reino Unido de Gran Bretaña e Irlanda del Norte", prefijo: "+44" },
    { pais: "Tanzania", prefijo: "+255" },
    { pais: "Estados Unidos", prefijo: "+1" },
    { pais: "Islas Vírgenes de los Estados Unidos", prefijo: "+1" },
    { pais: "Burkina Faso", prefijo: "+226" },
    { pais: "Uruguay", prefijo: "+598" },
    { pais: "Uzbekistán", prefijo: "+998" },
    { pais: "Venezuela", prefijo: "+58" },
    { pais: "Wallis y Futuna", prefijo: "+681" },
    { pais: "Samoa", prefijo: "+685" },
    { pais: "Yemen", prefijo: "+967" },
    { pais: "Zambia", prefijo: "+260" },
    { pais: "Congo", prefijo: "+242" },
    { pais: "Micronesia", prefijo: "+691" },
    { pais: "Macedonia", prefijo: "+389" },
    { pais: "Saint Kitts y Nevis", prefijo: "+1869" }
];
