/**
 * Catálogo Oficial CUPSRips Vigencia 2026 (Resolución 2706 de 2025 - Ministerio de Salud y Protección Social)
 * 
 * Marco Normativo:
 * - Resolución 2706 de 2025: Establece la Clasificación Única de Procedimientos en Salud (CUPS)
 *   vigente a partir del 1 de enero de 2026.
 * - Deroga expresamente desde el 1 de enero de 2026:
 *   * Resolución 2641 de 2024
 *   * Resolución 2689 de 2024
 *   * Resolución 756 de 2025
 * - Tabla de Referencia SISPRO: "CUPSRips"
 * - Esquema RIPS de validación: Documento Técnico 1 Versión 003 ("DT1-v003-2026")
 * 
 * Regla de Separación de Versiones:
 * - rips_schema_version = "DT1-v003-2026"
 * - cups_resolution = "2706-2025"
 * - cups_vigencia = "2026"
 * 
 * AVISO ARQUITECTÓNICO IMPORTANTE:
 * - Este archivo contiene un subconjunto controlado para pruebas arquitectónicas y fixtures de Fase 1.
 * - NO constituye la totalidad del Catálogo Nacional CUPSRips de producción.
 * - Para producción se implementará el mecanismo de carga/sincronización/versionamiento dinámico
 *   desde la tabla oficial SISPRO 'CUPSRips' mediante 'public.rips_catalogos'.
 * 
 * Regla de Clasificación Consulta vs Procedimiento:
 * - Proviene exclusivamente de la estructura oficial CUPSRips:
 *   * Capítulo 17 ("CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES") => Archivo RIPS 'AC' => consultas[]
 *   * Demás capítulos (01 a 16 quirúrgicos, 18 a 21 apoyo y prevención) => Archivo RIPS 'AP' => procedimientos[]
 * - CERO heurísticas basadas en prefijos de texto como startsWith("89").
 */

export const CUPS_RIPS_2026_METADATA = {
  catalogo: "CUPSRips",
  cups_resolution: "2706-2025",
  cups_vigencia: "2026",
  vigencia_desde: "2026-01-01",
  vigencia_hasta: null,
  fuente: "Ministerio de Salud y Protección Social / SISPRO - Tabla de Referencia CUPSRips (Resolución 2706 de 2025)",
  rips_schema_version: "DT1-v003-2026",
  es_fixture_pruebas: true,
  deroga: [
    "Resolución 2641 de 2024",
    "Resolución 2689 de 2024",
    "Resolución 756 de 2025",
  ],
};

/**
 * Tabla Maestra Oficial CUPSRips para Especialidades Odontológicas y Ambulatorias Relacionadas
 */
export const CUPS_RIPS_2026_ENTRIES = [
  // =========================================================================
  // CAPÍTULO 17: CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES (ARCHIVO AC)
  // =========================================================================
  {
    codigo: "890203",
    descripcionOficial: "CONSULTA DE PRIMERA VEZ POR ODONTOLOGÍA GENERAL",
    seccion: "03",
    capitulo: "17",
    capituloNombre: "CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES",
    grupo: "89",
    archivoRips: "AC",
    tipoRips: "consulta",
    correspondeBloqueConsultas: true,
    correspondeBloqueProcedimientos: false,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 17, Archivo AC)",
  },
  {
    codigo: "890303",
    descripcionOficial: "CONSULTA DE CONTROL O DE SEGUIMIENTO POR ODONTOLOGÍA GENERAL",
    seccion: "03",
    capitulo: "17",
    capituloNombre: "CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES",
    grupo: "89",
    archivoRips: "AC",
    tipoRips: "consulta",
    correspondeBloqueConsultas: true,
    correspondeBloqueProcedimientos: false,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 17, Archivo AC)",
  },
  {
    codigo: "890204",
    descripcionOficial: "CONSULTA DE PRIMERA VEZ POR OTRAS ESPECIALIDADES EN ODONTOLOGIA",
    seccion: "03",
    capitulo: "17",
    capituloNombre: "CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES",
    grupo: "89",
    archivoRips: "AC",
    tipoRips: "consulta",
    correspondeBloqueConsultas: true,
    correspondeBloqueProcedimientos: false,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 17, Archivo AC)",
  },
  {
    codigo: "890304",
    descripcionOficial: "CONSULTA DE CONTROL O DE SEGUIMIENTO POR OTRAS ESPECIALIDADES EN ODONTOLOGIA",
    seccion: "03",
    capitulo: "17",
    capituloNombre: "CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES",
    grupo: "89",
    archivoRips: "AC",
    tipoRips: "consulta",
    correspondeBloqueConsultas: true,
    correspondeBloqueProcedimientos: false,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 17, Archivo AC)",
  },
  {
    codigo: "890703",
    descripcionOficial: "CONSULTA DE ODONTOLOGÍA GENERAL DE URGENCIAS",
    seccion: "03",
    capitulo: "17",
    capituloNombre: "CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES",
    grupo: "89",
    archivoRips: "AC",
    tipoRips: "consulta",
    correspondeBloqueConsultas: true,
    correspondeBloqueProcedimientos: false,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 17, Archivo AC)",
  },
  {
    codigo: "890103",
    descripcionOficial: "ATENCIÓN (VISITA) DOMICILIARIA, POR ODONTOLOGÍA GENERAL",
    seccion: "03",
    capitulo: "17",
    capituloNombre: "CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES",
    grupo: "89",
    archivoRips: "AC",
    tipoRips: "consulta",
    correspondeBloqueConsultas: true,
    correspondeBloqueProcedimientos: false,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 17, Archivo AC)",
  },
  {
    codigo: "890201",
    descripcionOficial: "CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL",
    seccion: "03",
    capitulo: "17",
    capituloNombre: "CONSULTAS, INTERCONSULTAS, VISITAS Y VALORACIONES",
    grupo: "89",
    archivoRips: "AC",
    tipoRips: "consulta",
    correspondeBloqueConsultas: true,
    correspondeBloqueProcedimientos: false,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 17, Archivo AC)",
  },

  // =========================================================================
  // CAPÍTULO 07: PROCEDIMIENTOS EN CAVIDAD BUCAL Y DIENTES (ARCHIVO AP)
  // OPERATORIA / OBTURACIONES
  // =========================================================================
  {
    codigo: "232101",
    descripcionOficial: "OBTURACIÓN DENTAL CON AMALGAMA",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "232102",
    descripcionOficial: "OBTURACIÓN DENTAL CON RESINA DE FOTOCURADO",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "232103",
    descripcionOficial: "OBTURACIÓN DENTAL CON IONÓMERO DE VIDRIO",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "232104",
    descripcionOficial: "OBTURACIÓN DENTAL",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "232201",
    descripcionOficial: "OBTURACIÓN TEMPORAL POR DIENTE",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "232401",
    descripcionOficial: "RECONSTRUCCION DE DIENTE CON MATERIAL ESTETICO (CARILLA)",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },

  // CIRUGÍA ORAL (ARCHIVO AP)
  {
    codigo: "230101",
    descripcionOficial: "EXODONCIA DE DIENTE PERMANENTE UNIRRADICULAR",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "230102",
    descripcionOficial: "EXODONCIA DE DIENTE PERMANENTE MULTIRRADICULAR",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "230201",
    descripcionOficial: "EXODONCIA DE DIENTE TEMPORAL UNIRRADICULAR",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "230202",
    descripcionOficial: "EXODONCIA DE DIENTE TEMPORAL MULTIRRADICULAR",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "231100",
    descripcionOficial: "EXODONCIA QUIRURGICA DE DIENTES MAXILARES",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "231200",
    descripcionOficial: "EXODONCIA QUIRURGICA DE DIENTES MANDIBULARES",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "231301",
    descripcionOficial: "EXODONCIA DE DIENTE INCLUIDO",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },

  // ENDODONCIA (ARCHIVO AP)
  {
    codigo: "237101",
    descripcionOficial: "TRATAMIENTO DE CONDUCTOS EN DIENTES UNIRRADICULARES",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "237102",
    descripcionOficial: "TRATAMIENTO DE CONDUCTOS EN DIENTES BIRRADICULARES",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "237103",
    descripcionOficial: "TRATAMIENTO DE CONDUCTOS EN DIENTES MULTIRRADICULARES",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "237201",
    descripcionOficial: "RETRATAMIENTO DE CONDUCTOS EN DIENTES UNIRRADICULARES",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "237202",
    descripcionOficial: "RETRATAMIENTO DE CONDUCTOS EN DIENTES BIRRADICULARES",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "237203",
    descripcionOficial: "RETRATAMIENTO DE CONDUCTOS EN DIENTES MULTIRRADICULARES",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "23",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },

  // PERIODONCIA (ARCHIVO AP)
  {
    codigo: "243101",
    descripcionOficial: "CURETAJE Y ALISADO RADICULAR CAMPO CERRADO (POR SEXTANTE)",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "24",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },
  {
    codigo: "242201",
    descripcionOficial: "GINGIVECTOMIA (POR CUADRANTE)",
    seccion: "01",
    capitulo: "07",
    capituloNombre: "PROCEDIMIENTOS EN LA CAVIDAD BUCAL Y DIENTES",
    grupo: "24",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 07, Archivo AP)",
  },

  // IMÁGENES DIAGNÓSTICAS / RADIOLOGÍA (ARCHIVO AP)
  {
    codigo: "870001",
    descripcionOficial: "RADIOGRAFIA INTRAORAL: PERIAPICAL MILIMETRADA",
    seccion: "02",
    capitulo: "19",
    capituloNombre: "IMÁGENES DIAGNÓSTICAS",
    grupo: "87",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 19, Archivo AP)",
  },
  {
    codigo: "870112",
    descripcionOficial: "RADIOGRAFIA PANORAMICA DE MANDIBULA Y MAXILAR",
    seccion: "02",
    capitulo: "19",
    capituloNombre: "IMÁGENES DIAGNÓSTICAS",
    grupo: "87",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 19, Archivo AP)",
  },

  // PREVENCIÓN Y PROMOCIÓN (ARCHIVO AP)
  {
    codigo: "997107",
    descripcionOficial: "APLICACIÓN DE SELLANTES",
    seccion: "02",
    capitulo: "21",
    capituloNombre: "PROCEDIMIENTOS MISCELÁNEOS, DE PROTECCIÓN ESPECÍFICA Y DETECCIÓN TEMPRANA",
    grupo: "99",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 21, Archivo AP)",
  },
  {
    codigo: "997101",
    descripcionOficial: "PROFILAXIS DENTAL",
    seccion: "02",
    capitulo: "21",
    capituloNombre: "PROCEDIMIENTOS MISCELÁNEOS, DE PROTECCIÓN ESPECÍFICA Y DETECCIÓN TEMPRANA",
    grupo: "99",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 21, Archivo AP)",
  },
  {
    codigo: "990112",
    descripcionOficial: "DETARTRAJE SUPRAGINGIVAL",
    seccion: "02",
    capitulo: "21",
    capituloNombre: "PROCEDIMIENTOS MISCELÁNEOS, DE PROTECCIÓN ESPECÍFICA Y DETECCIÓN TEMPRANA",
    grupo: "99",
    archivoRips: "AP",
    tipoRips: "procedimiento",
    correspondeBloqueConsultas: false,
    correspondeBloqueProcedimientos: true,
    activo: true,
    vigenciaDesde: "2026-01-01",
    vigenciaHasta: null,
    resolucionCups: "2706-2025",
    fuenteOficial: "MinSalud / SISPRO - CUPSRips 2026 (Capítulo 21, Archivo AP)",
  },
];

// Mapa en memoria para búsqueda ultra-rápida indexada O(1)
const indexedCupsMap = new Map(
  CUPS_RIPS_2026_ENTRIES.map(e => [e.codigo, Object.freeze(e)])
);

/**
 * Consulta un código en el catálogo independiente CUPSRips 2026.
 * 
 * @param {string} cupsCode Código CUPS de 6 caracteres
 * @returns {Promise<{
 *   codigo: string,
 *   descripcionOficial: string|null,
 *   tipoRips: 'consulta'|'procedimiento'|null,
 *   archivoRips: 'AC'|'AP'|null,
 *   correspondeBloqueConsultas: boolean,
 *   correspondeBloqueProcedimientos: boolean,
 *   seccion: string|null,
 *   capitulo: string|null,
 *   capituloNombre: string|null,
 *   activo: boolean,
 *   vigenciaDesde: string|null,
 *   vigenciaHasta: string|null,
 *   resolucionCups: string,
 *   ripsSchemaVersion: string,
 *   fuenteOficial: string|null,
 *   exists: boolean,
 *   active: boolean,
 *   error: string|null
 * }>}
 */
export async function getCupsRipsRecord(cupsCode) {
  const cleanCode = String(cupsCode || "").trim().toUpperCase();
  if (!cleanCode) {
    return {
      codigo: "",
      descripcionOficial: null,
      tipoRips: null,
      archivoRips: null,
      correspondeBloqueConsultas: false,
      correspondeBloqueProcedimientos: false,
      seccion: null,
      capitulo: null,
      capituloNombre: null,
      activo: false,
      vigenciaDesde: null,
      vigenciaHasta: null,
      resolucionCups: CUPS_RIPS_2026_METADATA.cups_resolution,
      ripsSchemaVersion: CUPS_RIPS_2026_METADATA.rips_schema_version,
      fuenteOficial: null,
      exists: false,
      active: false,
      error: "Código CUPS vacío.",
    };
  }

  const entry = indexedCupsMap.get(cleanCode);

  if (!entry) {
    return {
      codigo: cleanCode,
      descripcionOficial: null,
      tipoRips: null,
      archivoRips: null,
      correspondeBloqueConsultas: false,
      correspondeBloqueProcedimientos: false,
      seccion: null,
      capitulo: null,
      capituloNombre: null,
      activo: false,
      vigenciaDesde: null,
      vigenciaHasta: null,
      resolucionCups: CUPS_RIPS_2026_METADATA.cups_resolution,
      ripsSchemaVersion: CUPS_RIPS_2026_METADATA.rips_schema_version,
      fuenteOficial: null,
      exists: false,
      active: false,
      error: `El código CUPS '${cleanCode}' no existe en el catálogo oficial CUPSRips vigente (Resolución ${CUPS_RIPS_2026_METADATA.cups_resolution}).`,
    };
  }

  if (!entry.activo) {
    return {
      ...entry,
      ripsSchemaVersion: CUPS_RIPS_2026_METADATA.rips_schema_version,
      exists: true,
      active: false,
      error: `El código CUPS '${cleanCode}' (${entry.descripcionOficial}) se encuentra inactivo/no vigente en la tabla oficial CUPSRips (Resolución ${CUPS_RIPS_2026_METADATA.cups_resolution}).`,
    };
  }

  return {
    ...entry,
    ripsSchemaVersion: CUPS_RIPS_2026_METADATA.rips_schema_version,
    exists: true,
    active: true,
    error: null,
  };
}

export default {
  CUPS_RIPS_2026_METADATA,
  CUPS_RIPS_2026_ENTRIES,
  getCupsRipsRecord,
};
